version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: csv_agent_app
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: csv_agent_nginx
    ports:
      - "80:80"
    depends_on:
      - app
